spring:
  application:
    name: wishlist-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wishlist_db
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          format_sql: true

server:
    port: 8082